### Creates a new patient entity
POST http://lb-5cbf238c.elb.localhost.localstack.cloud:4004/api/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Andrei Andreescu Kafka",
  "email": "kafka@example.com",
  "address": "123 Bucuresti",
  "dateOfBirth": "2000-03-02",
  "registeredDate": "2026-01-02"
}

###